### ISSUE TITLE
Low / medium / high meaning

### ISSUE THREAD

**Issue by jgarvin** [oseparovic/fodmap_list#5]
It seems like the raw data should be whatever was actually measured in a lab -- I don't know that the unit actually is though (ppm?). Low/medium/high seems like mixing a UI issue (should we tell the user this is a green/yellow/red light food) into the data. Or is this how it actually gets published?

**Comment by oseparovic** [comment]
Unfortunately we don't have access to that. This is just a helper app. The data in this app is aggregated from free sources on the web. Monash has paywalled most of their lab data
